spring.application.name=review-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://review-db:3306/review_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8082
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

booking-service.url=${BOOKING_SERVICE_URL:http://booking-service:8081}